/**
 * Nexora — generate the licence console as a standalone page
 * ======================================================================
 * The console is ONE page, and it lives in ADMIN_HTML in src/admin.js.
 * This writes that same page out as a file, so it can be hosted where a
 * browser will actually render it.
 *
 * Why it has to be hosted elsewhere at all: Supabase's Edge runtime
 * rewrites `text/html` to `text/plain` — its own documentation says so,
 * and the deployed function proves it — so `/admin` from a function
 * arrives as source code. Supabase Storage serves real content types, so
 * the page goes there and `/admin` on the function redirects to it.
 *
 * It is GENERATED, never hand-maintained. A second copy of a 32 KB page
 * would drift from the first, and this project has already paid for a
 * duplicated thing drifting once.
 *
 * The only difference from what Render serves is one line: the address of
 * /admin/api/*, which a page on another origin cannot reach by a relative
 * path. The page reads window.NEXORA_API_BASE and CORS already allows it
 * (`access-control-allow-headers: x-admin-key`). No secret is baked in —
 * the admin key is typed by the owner and never leaves the browser tab.
 *
 * Run:  node build-console.mjs [api-base-url]
 */
import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT = resolve(HERE, 'build/console/index.html');

const API_BASE = (process.argv[2] || process.env.NEXORA_API_BASE || '').trim().replace(/\/+$/, '');
if (!API_BASE) {
  throw new Error('Give the service address, e.g.\n'
    + '  node build-console.mjs https://dzbzcwmxyenztowzcukc.supabase.co/functions/v1/nexora');
}
if (!/^https:\/\//.test(API_BASE)) {
  /* The page is hosted on one origin and talks to another. Over http the
     admin key would cross the network in clear, and a browser on an https
     page would refuse the request anyway. */
  throw new Error('the service address must be https, got: ' + API_BASE);
}

/* ADMIN_HTML is read at module scope, and admin.js reads NEXORA_ADMIN_KEY
   at module scope too. Nothing here uses it, but it must not be empty in
   a way that looks like a configured blank. */
process.env.NEXORA_ADMIN_KEY = process.env.NEXORA_ADMIN_KEY || 'not-used-by-this-build';
const { ADMIN_HTML } = await import('./src/admin.js');

const marker = '<script>';
const at = ADMIN_HTML.indexOf(marker);
if (at < 0) throw new Error('the console page has no <script> — admin.js has changed shape');

const injected = '<script>\n'
  + '/* Generated by build-console.mjs. The page itself is ADMIN_HTML in\n'
  + '   src/admin.js; this line is the only thing added, and it is what\n'
  + '   lets a page on one origin reach the service on another. */\n'
  + 'window.NEXORA_API_BASE = ' + JSON.stringify(API_BASE) + ';\n'
  + '</script>\n';

const page = ADMIN_HTML.slice(0, at) + injected + ADMIN_HTML.slice(at);

/* If the page ever stops honouring it, the console would silently ask its
   own origin for /admin/api/* and answer "Request failed (404)" with no
   clue why. Check rather than hope. */
if (!/window\.NEXORA_API_BASE\s*\|\|/.test(page)) {
  throw new Error('the page does not read window.NEXORA_API_BASE — admin.js and this script are out of step');
}

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, page, 'utf8');
console.log('wrote ' + OUT);
console.log((page.length / 1024).toFixed(1) + ' KB, pointing at ' + API_BASE);
