/**
 * Nexora — build the Supabase Edge Function bundle
 * ======================================================================
 * One file out, because a function is uploaded as a unit and a dozen
 * small modules buy nothing.
 *
 * Two substitutions happen here and nowhere else, so that the source
 * tree stays honest:
 *
 *   src/pgmini.js  ->  src/pgdeno.js
 *       pgmini speaks the Postgres wire protocol itself over node:net
 *       and node:tls. Importing either in the Edge runtime makes the
 *       function boot and then die with no error at all (proved in the
 *       spike). pgdeno is the same interface over npm:postgres.
 *
 *   'postgres'     ->  'npm:postgres@<the version tested here>'
 *       Left bare, Deno cannot resolve it. Bundled in, it drags node:net
 *       back with it. As an npm: specifier the runtime resolves it
 *       natively — which is the arrangement the spike proved works.
 *
 * Everything else in the bundle is this project's own source.
 *
 * Run:  node build-edge.mjs
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import * as esbuild from 'esbuild-wasm';

const HERE = dirname(fileURLToPath(import.meta.url));

/* The layout `supabase functions deploy nexora` expects, so the same
   output is deployed by the CLI, by CI and by hand. */
const FUNCTION = 'nexora';
const OUT = resolve(HERE, 'supabase/functions/' + FUNCTION + '/index.ts');

/* The postgres version is pinned HERE, deliberately, rather than taken
   from whatever npm last installed: what the suites ran against is what
   gets deployed. To move it, change this line, re-run the suites against
   the new package, then rebuild. */
const PG_VERSION = '3.4.9';

/* And say so loudly if the copy the tests used is not that one. */
const installed = ['../node_modules/postgres/package.json', 'node_modules/postgres/package.json']
  .map((p) => { try { return JSON.parse(readFileSync(resolve(HERE, p), 'utf8')).version; } catch (e) { return null; } })
  .find(Boolean);
if (installed && installed !== PG_VERSION) {
  throw new Error('postgres ' + installed + ' is installed but the bundle pins ' + PG_VERSION
    + '. The tests would be proving a different package from the one deployed.');
}

await esbuild.initialize({ wasmURL: undefined });

/* pgmini -> pgdeno, without a line of #if in the source. */
const denoClient = {
  name: 'nexora-deno-client',
  setup(build) {
    build.onResolve({ filter: /(^|\/)pgmini\.js$/ }, (args) => ({
      path: resolve(HERE, 'src/pgdeno.js')
    }));
  }
};

const result = await esbuild.build({
  entryPoints: [resolve(HERE, 'edge/entry.js')],
  bundle: true,
  format: 'esm',
  platform: 'neutral',
  target: 'es2022',
  mainFields: ['module', 'main'],
  conditions: ['import', 'node'],
  external: ['postgres', 'node:*'],
  plugins: [denoClient],
  /* One upload, and the console's HTML is most of it. Minified, because
     this file is generated and read by a runtime, not by a person. */
  minify: true,
  legalComments: 'none',
  write: false,
  metafile: true,
  logLevel: 'warning'
});

/* No file in this bundle may WRITE to process.env.
   The Edge runtime refuses it — "NotSupported: The operation is not
   supported", from inside the node:process shim, thrown on the event loop
   AFTER the function has booted. So the function starts in 22 ms and then
   dies, and every route answers 500 with an empty body. Node allows the
   write, so no suite can catch it; this is checked here instead, against
   the files esbuild actually pulled in rather than a guessed list. */
const assigns = /process\s*\.\s*env\s*(?:\.\s*[A-Za-z_$][\w$]*|\[[^\]]*\])\s*=(?!=)/;
const offenders = Object.keys(result.metafile.inputs)
  .filter((f) => !f.includes('node_modules'))
  .filter((f) => { try { return assigns.test(readFileSync(resolve(HERE, f), 'utf8')); } catch (e) { return false; } });
if (offenders.length) {
  throw new Error('these files assign to process.env, which the Edge runtime refuses: ' + offenders.join(', '));
}

let code = result.outputFiles[0].text;

const before = code;
code = code.replace(/(from\s*|import\s*\()(["'])postgres\2/g, (_, pre, q) => pre + q + 'npm:postgres@' + PG_VERSION + q);
if (code === before) throw new Error('the postgres import was not found in the bundle — the specifier rewrite silently did nothing');
if (/["']node:(net|tls)["']/.test(code)) throw new Error('node:net or node:tls reached the bundle — the Edge runtime cannot run this');

/* Plain ASCII, header included. esbuild already escapes every non-ASCII
   character in the code itself (the console's HTML is full of them), and
   a file that is ASCII from end to end can be split on any boundary
   without splitting a character in half — which is how it is uploaded. */
const header = '// Nexora licence service - generated by build-edge.mjs. Do not edit.\n'
  + '// Sources: server/edge/entry.js + server/src/*  |  client: pgdeno.js on npm:postgres@' + PG_VERSION + '\n';
code = header + code;
// eslint-disable-next-line no-control-regex
if (/[^\x00-\x7F]/.test(code)) throw new Error('the bundle is not pure ASCII');

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, code);

/* The CLI wants a project directory, and verify_jwt belongs in it rather
   than in a flag someone can forget. The service authenticates itself —
   its own licence tokens, its own admin key — and /health, /v1/activate
   and /v1/register MUST be reachable by a machine that has no token yet.
   A Supabase JWT gate in front of those would lock out every customer. */
writeFileSync(resolve(HERE, 'supabase/config.toml'),
  '# Generated by build-edge.mjs. Do not edit.\n'
  + 'project_id = "nexora"\n\n'
  + '[functions.' + FUNCTION + ']\n'
  + 'verify_jwt = false\n'
  + 'entrypoint = "./functions/' + FUNCTION + '/index.ts"\n');

console.log('wrote ' + OUT);
console.log((code.length / 1024).toFixed(1) + ' KB, postgres pinned to ' + PG_VERSION);
await esbuild.stop();
